version: '3.8'

services:
  java-app:
    build: .
    ports:
      - "8080:8080"  # Adjust the port based on your application's configuration
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network
    depends_on:
      - java-app

networks:
  app-network:
    driver: bridge
