global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'java-application'
    static_configs:
      - targets: ['java-app:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:7071']  # This assumes Kafka is running as a service in Docker. Adjust if it’s external.

  - job_name: 'spring-application'
    static_configs:
      - targets: ['java-app:8080']  # Assuming this is the same as 'java-application'
